apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres/secret.yaml
  - postgres/configmap-init.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
  - zabbix/server.yaml
  - zabbix/web.yaml
  - zabbix/agent2-daemonset.yaml
  - grafana/configmaps.yaml
  - grafana/configmap-dashboard-json.yaml
  - grafana/deployment.yaml
