apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: conexao-solidaria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
          ports:
            - containerPort: 10051
          env:
            - name: DB_SERVER_HOST
              value: postgres
            - name: POSTGRES_USER
              value: zabbix
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: ZABBIX_POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: zabbix
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits: { cpu: 500m, memory: 512Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: conexao-solidaria
spec:
  selector:
    app: zabbix-server
  ports:
    - port: 10051
      targetPort: 10051
