apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: conexao-solidaria
type: Opaque
stringData:
  POSTGRES_USER: conexaosolidaria
  POSTGRES_PASSWORD: conexaosolidaria
  POSTGRES_DB: conexaosolidaria
  ZABBIX_POSTGRES_PASSWORD: zabbix
