apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: conexao-solidaria

resources:
- secret.yaml
- service.yaml
- ingress.yaml
- rollout.yaml

images:
- name: ghcr.io/marcarinivinicius/conexao-solidaria-campaign-api
  newName: ghcr.io/marcarinivinicius/conexao-solidaria-campaign-api
  newTag: v0.2.2
