# Service adicional (nao mexe no argocd-server oficial do install.yaml)
# so pra dar uma porta fixa de acesso externo sem depender de port-forward.
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 30443
  type: NodePort
